Fix TypeError when using `bitscrub -l ...`
    listing.write(" ".join([t, checksum_s, time2iso(mtime), size_s, p]) + "\n")
TypeError: a bytes-like object is required, not 'str'