Handle a very strange error on some files that might be due to a 64-bit CPython bug
File "[...]\Checksummer\checksummer\winfile.py", line 159, in seek
  ctypes.c_long(whence)
WindowsError: exception: access violation writing 0x0000000100000000